# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd83f15767bd11c89ae6d568ef7c98e14a63f04e9097cda995f54a6de10512028050eb0c840dd73cc5c137008b6d4039673306ae6ff14f7c2e7f0a543d48e54f

test:
  secret_key_base: 92712867efdb70cb064f1c0a419d089e6c7d9b41557064710497f2ea088a93d17445f325256116846f34798e7c5b78c6cb2296fccb7fec891e1b0878a833ad89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
